### ISSUE TITLE
curation error? and possible useful addition

### ISSUE THREAD

**Issue by schristley** [sfu-ireceptor/dataloading-curation#7] opened 2020-07-02 14:54 UTC
Not sure this is the right place to report questions about study metadata...

Anyways, I was looking through some cancer studies, in particular `study_id:PRJNA330606` and I noticed for `repertoire_id:48` that the `sequencing_files` looked incorrect. The `filename` field contains multiple file names, but I believe there should only be one?

```
          "sequencing_files": {
            "file_type": "fasta",
            "filename": "SRR4084218_aa_merged.fasta, SRR4084218_ab_merged.fasta, SRR4084218_ac_merged.fasta, SRR4084218_ad_merged.fasta",
            "read_direction": null,
            "read_length": null,
            "paired_filename": null,
            "paired_read_direction": null,
            "paired_read_length": null
          }
```

Also, I was trying to relate this back to the raw data in SRA. I can see `SRR4084218` is in the filenames, so I assume that's it. One nice addition for your curation might be to put `SRR4084218` in the `sequencing_run_id` field. That would make the link more explicit.

Which led to another question. The SRA record shows the raw data is paired-end files with 101 read lengths, but that's not what is in the `sequencing_files` above, so maybe you didn't process the raw data from SRA but got some pre-processed data from somewhere else?

**Comment by bcorrie** [comment] 2020-07-03 18:31
Good questions @schristley 8-)

Essentially the repertoire metadata in our curation process maps to how things were processed and loaded into the iReceptor repository and provides us with data provenance. So the filenames in sequencing files for our curation process in this case at least, are the files that were processed by the annotation tool and were the output of our QC and pairing process. There are multiple files because the data is large and some of the software is challenged with files of that size. Since multiple files are how we perform the curation/processing, we track multiple files in the repertoire metadata. 

We maintain these files as a step in our curation process (but are not available through the repository). With that said, you should essentially be able to reproduce the data in the fasta files from the repository if you wanted to. 

If you look at paired_read_assembly and data_processing_protocols it describes how the files were paired. It is the paired files that are loaded into the repository and the data_processing_files and the sequence_files.file_name typically are 1-1 in our curation process. 

Although the AIRR standard is suggestive that this should be a single file, that seems somewhat restrictive in terms of forcing the researcher to limit their curation process in that way... So we stretched that definition somewhat so that our sequencing files and the data processing files matched...

Our repertoire metadata describes the files as loaded into the repository as opposed to exactly describing the files that are stored on SRA by the authors. This helps us track how things were processed and provides us with valuable links between the fasta files that were annotated and the annotation data. From a reproducibility and data provenance perspective for our curation pipeline that was deemed the most critical, in particular because we document how we got from the raw files from SRA to paired files that were annotated and curated in other fields.

WRT sequence_run_id, I had interpreted that as something that was a result of something that was returned from the sequencing facility, which would apply to many fasta files. It didn't seem like it was associated to an SRA run based on the explanation and example... But I am no expert.

Our curation process and data provenance approach is described here:
http://www.ireceptor.org/node/114

Of course, with all of the above stated, this study in particular was curated three years ago in the summer of 2017, so our curation process has evolved a bit since then. It isn't too different today though...

**Comment by schristley** [comment] 2020-07-03 19:01
@bcorrie thanks for info. I feel the tie to SRA is too weak at the moment, specifically for MiAIRR, so I created [ticket](https://github.com/airr-community/airr-standards/issues/435) where we can make this more explicit. It may be the MiAIRR was meant to be an explicit link with an SRA run and we just weren't interpreting it so...

> WRT sequence_run_id, I had interpreted that as something that was a result of something that was returned from the sequencing facility, which would apply to many fasta files. It didn't seem like it was associated to an SRA run based on the explanation and example... But I am no expert.

We should get clarification from MiAIRR, but I think that "would apply to many fasta files" is exactly what it should not be. I think that has the potential to be abused, i.e. people combine together or separate files that they shouldn't in order to "be lazy". For example, combine them so they don't have to create separate sample processing records, even though the samples have really been processed differently!

But I do understand there are complexities here, like some sequencing protocols will automatically demultiplex samples into multiple files, so we do need to handle that, though in that case they really are different sample processing records but then how is that recorded in SRA...

> that seems somewhat restrictive in terms of forcing the researcher to limit their curation process in that way... 

I'm a little bit leary of that statement. I hope that we make the semantics clear, that it won't be limiting while also providing us with replication, which is sorely lacking on the data processing side right now.

**Comment by bcorrie** [comment] 2020-07-06 19:53
I will close this and we can take up the discussion in the AIRR github issue https://github.com/airr-community/airr-standards/issues/435

**Closed by bcorrie** 2020-07-06 19:53 UTC
